[[deqp]]
deqp = "/deqp-gles/modules/gles31/deqp-gles31"
caselists = ["/deqp-gles/mustpass/gles31-main.txt"]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]
version_check = "GL ES 3.1.*git"
renderer_check = "V3D 4.2.14"
prefix = "ubsan-"

[[deqp]]
deqp = "/deqp-gles/external/openglcts/modules/glcts"
caselists = [
    "/deqp-gles/mustpass/gles31-khr-main.txt",
]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]
prefix = "ubsan-"

# CTS enables GPU reset detection by default, which requires
# KHR_robustness support.
# Since this extension isn't implemented, disable it using
# "--deqp-terminate-on-device-lost=disable".
[[deqp]]
deqp = "/deqp-gl/external/openglcts/modules/glcts"
caselists = ["/deqp-gl/mustpass/gl31-main.txt"]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-terminate-on-device-lost=disable",
    "--deqp-visibility=hidden",
]
prefix = "ubsan-"
