variables:
  CONDITIONAL_BUILD_ANDROID_CTS_TAG: 7dc065d0dbc5af2614ac81d805e5a15f
  CONDITIONAL_BUILD_ANGLE_TAG: f62910e55be46e37cc867d037e4a8121
  CONDITIONAL_BUILD_CROSVM_TAG: 0f59350b1052bdbb28b65a832b494377
  CONDITIONAL_BUILD_FLUSTER_TAG: 3bc3afd7468e106afcbfd569a85f34f9
  CONDITIONAL_BUILD_PIGLIT_TAG: 827b708ab7309721395ea28cec512968
  CONDITIONAL_BUILD_VKD3D_PROTON_TAG: 82cadf35246e64a8228bf759c9c19e5b
