variables:
  CONDITIONAL_BUILD_ANDROID_CTS_TAG: b018634d732f438027ec58c0383615e7
  CONDITIONAL_BUILD_ANGLE_TAG: efd57e99d51361944f87b9466356b0ce
  CONDITIONAL_BUILD_CROSVM_TAG: d11bef2a6b529802b5deaeaa490fd4d9
  CONDITIONAL_BUILD_FLUSTER_TAG: e13f8521875ebd70e207ec0f6f3d3e5b
  CONDITIONAL_BUILD_PIGLIT_TAG: 21ab2c66f54777163dd038dc4cfcfde6
  CONDITIONAL_BUILD_VKD3D_PROTON_TAG: 1ba830680bde0e04c0488183e1054f8d
