variables:
  CONDITIONAL_BUILD_ANDROID_CTS_TAG: b018634d732f438027ec58c0383615e7
  CONDITIONAL_BUILD_ANGLE_TAG: ccde6a2b0d3509c2a8fc459cbd936ac4
  CONDITIONAL_BUILD_CROSVM_TAG: 4079babd375b09761d59eacb25a0598a
  CONDITIONAL_BUILD_FLUSTER_TAG: e13f8521875ebd70e207ec0f6f3d3e5b
  CONDITIONAL_BUILD_PIGLIT_TAG: 31939f3b6f2a619277594e671c9fbbff
  CONDITIONAL_BUILD_VKD3D_PROTON_TAG: 167feb963fb512795aeddc9d1588bc7c
