variables:
  CONDITIONAL_BUILD_ANDROID_CTS_TAG: b018634d732f438027ec58c0383615e7
  CONDITIONAL_BUILD_ANGLE_TAG: 6ade8a52dd596b3de5dee62006bf4fc3
  CONDITIONAL_BUILD_CROSVM_TAG: 4c61f9707203afca91db3efeb57175db
  CONDITIONAL_BUILD_FLUSTER_TAG: e13f8521875ebd70e207ec0f6f3d3e5b
  CONDITIONAL_BUILD_PIGLIT_TAG: 8eafc8b1214f64f0d9a298e7a57bc87a
  CONDITIONAL_BUILD_VKD3D_PROTON_TAG: 072beee85d89e75f9a81664b77198b92
