variables:
  CONDITIONAL_BUILD_ANDROID_CTS_TAG: b018634d732f438027ec58c0383615e7
  CONDITIONAL_BUILD_ANGLE_TAG: efd57e99d51361944f87b9466356b0ce
  CONDITIONAL_BUILD_CROSVM_TAG: 4c61f9707203afca91db3efeb57175db
  CONDITIONAL_BUILD_FLUSTER_TAG: e13f8521875ebd70e207ec0f6f3d3e5b
  CONDITIONAL_BUILD_PIGLIT_TAG: 21ab2c66f54777163dd038dc4cfcfde6
  CONDITIONAL_BUILD_VKD3D_PROTON_TAG: 072beee85d89e75f9a81664b77198b92
